name: "6 - Deploy Backend Java no EKS"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::749000351410:role/github-carina-devops-pipe
          aws-region: us-east-1

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
            --name ppeks-cluster \
            --region us-east-1

      - name: Ler outputs do RDS via tfstate S3
        id: rds
        run: |
          RDS_HOST=$(aws s3 cp s3://tfstate-ppeks/rds/terraform.tfstate - | \
            python3 -c "import sys,json; s=json.load(sys.stdin); print(s['outputs']['rds_endpoint']['value'])")
          RDS_DB=$(aws s3 cp s3://tfstate-ppeks/rds/terraform.tfstate - | \
            python3 -c "import sys,json; s=json.load(sys.stdin); print(s['outputs']['rds_db_name']['value'])")
          echo "rds_host=$RDS_HOST" >> $GITHUB_OUTPUT
          echo "rds_db=$RDS_DB"     >> $GITHUB_OUTPUT

      - name: Criar namespace se não existir
        run: |
          kubectl get namespace appback || kubectl create namespace appback

      - name: Criar/atualizar Secret com credenciais do banco
        run: |
          USERNAME=$(aws ssm get-parameter --name "/db/username" --query "Parameter.Value" --output text)
          PASSWORD=$(aws ssm get-parameter --name "/db/password" --with-decryption --query "Parameter.Value" --output text)

          kubectl create secret generic app-db-credentials \
            --from-literal=SPRING_DATASOURCE_USERNAME=$USERNAME \
            --from-literal=SPRING_DATASOURCE_PASSWORD=$PASSWORD \
            --namespace appback \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy backend com Helm
        run: |
          helm upgrade --install java-back ./charts/java-back \
            --namespace appback \
            --set env.POSTGRES_HOST=${{ steps.rds.outputs.rds_host }} \
            --set env.POSTGRES_DB=${{ steps.rds.outputs.rds_db }}